name: estimagic

channels:
  - conda-forge
  - defaults
  - opensourceeconomics

dependencies:

  - python=3.7
  - pip=19.0.3
  - anaconda-client
  - bokeh>=1.3
  - click
  - conda-build
  - conda-verify
  - fuzzywuzzy
  - joblib
  - jupyterlab
  - nbsphinx
  - numba >= 0.12
  - numdifftools>= 0.9.20
  - numpy=1.16
  - pandas>=0.24,<1.0
  - pdbpp
  - petsc4py>=3.11
  - pygmo=2.10
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - restructuredtext_lint
  - scipy=1.2.1
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - sqlalchemy>=1.3
  - tox-conda
  - pip:
    - black
    - blackcellmagic
    - bump2version
    - pre-commit
